# core/docker-compose.debug.yml
# This file extends the main docker-compose.yml to enable debugging

version: "3.8"

services:
  librechat:
    # Override command to enable Node.js debugging
    command: ["npm", "run", "backend:dev", "--", "--inspect=0.0.0.0:9229"]
    # Add debug port
    ports:
      - "${HOST_PORT_LIBRECHAT:-3080}:3080"
      - "9229:9229"
    # Add debug environment variables
    environment:
      - NODE_ENV=development
      - DEBUG=librechat:*
      - VITE_API_HOST=http://localhost:${HOST_PORT_LIBRECHAT:-3080}